.PHONY: all build clean dev dist install lint preview mod wire swagger test start api

all: build

install:
	pnpm install

mod: install

wire:

swagger:

test:
	pnpm lint

start:
	pnpm start

api:
	pnpm api

dev:
	pnpm dev

lint:
	pnpm lint

build:
	pnpm build

dist: build

preview:
	pnpm preview

clean:
	rm -rf dist
	mkdir -p dist
