// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"clearbill/mgr/server/internal/app/action"
	"clearbill/mgr/server/internal/app/bll"
	"clearbill/mgr/server/internal/app/config"
	"clearbill/mgr/server/internal/app/dal"
	"clearbill/mgr/server/internal/app/db"
)

// Injectors from wire.go:

func BuildInjector(cfg config.Config) (*Injector, error) {
	gormDB, err := db.InitDBClient(cfg)
	if err != nil {
		return nil, err
	}
	engine := InitGinEngine(cfg)
	userDAL := dal.NewUserDAL(gormDB)
	sessionDAL := dal.NewSessionDAL(gormDB)
	apiTokenDAL := dal.NewAPITokenDAL(gormDB)
	authService := bll.NewAuthService(userDAL, sessionDAL, apiTokenDAL)
	authAction := action.NewAuthAction(authService)
	systemDAL := dal.NewSystemDAL()
	systemService := bll.NewSystemService(systemDAL)
	systemAction := action.NewSystemAction(systemService)
	billingDAL := dal.NewBillingDAL()
	billingService := bll.NewBillingService(billingDAL)
	billingAction := action.NewBillingAction(billingService)
	tenantDAL := dal.NewTenantDAL(gormDB)
	tenantService := bll.NewTenantService(tenantDAL, userDAL)
	tenantAction := action.NewTenantAction(tenantService)
	userService := bll.NewUserService(userDAL, tenantDAL)
	userAction := action.NewUserAction(userService)
	router := InitRouter(cfg, authService, authAction, systemAction, billingAction, tenantAction, userAction, engine)
	injector := &Injector{
		Config:         cfg,
		DBClient:       gormDB,
		Engine:         engine,
		Router:         router,
		APITokenDAL:    apiTokenDAL,
		AuthAction:     authAction,
		SystemAction:   systemAction,
		BillingAction:  billingAction,
		TenantAction:   tenantAction,
		UserAction:     userAction,
		AuthService:    authService,
		SystemService:  systemService,
		BillingService: billingService,
		TenantService:  tenantService,
		UserService:    userService,
		SystemDAL:      systemDAL,
		BillingDAL:     billingDAL,
		TenantDAL:      tenantDAL,
		UserDAL:        userDAL,
		SessionDAL:     sessionDAL,
	}
	return injector, nil
}
