// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"clearbill/mgr/server/internal/app/action"
	"clearbill/mgr/server/internal/app/bll"
	"clearbill/mgr/server/internal/app/config"
	"clearbill/mgr/server/internal/app/dal"
	"clearbill/mgr/server/internal/app/db"
)

// Injectors from wire.go:

func BuildInjector(cfg config.Config) (*Injector, error) {
	gormDB, err := db.InitDBClient(cfg)
	if err != nil {
		return nil, err
	}
	engine := InitGinEngine(cfg)
	systemDAL := dal.NewSystemDAL()
	systemService := bll.NewSystemService(systemDAL)
	systemAction := action.NewSystemAction(systemService)
	billingDAL := dal.NewBillingDAL()
	billingService := bll.NewBillingService(billingDAL)
	billingAction := action.NewBillingAction(billingService)
	tenantDAL := dal.NewTenantDAL(gormDB)
	tenantService := bll.NewTenantService(tenantDAL)
	tenantAction := action.NewTenantAction(tenantService)
	router := InitRouter(cfg, systemAction, billingAction, tenantAction, engine)
	injector := &Injector{
		Config:         cfg,
		DBClient:       gormDB,
		Engine:         engine,
		Router:         router,
		SystemAction:   systemAction,
		BillingAction:  billingAction,
		TenantAction:   tenantAction,
		SystemService:  systemService,
		BillingService: billingService,
		TenantService:  tenantService,
		SystemDAL:      systemDAL,
		BillingDAL:     billingDAL,
		TenantDAL:      tenantDAL,
	}
	return injector, nil
}
