// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"clearbill/mgr/server/internal/app/action"
	"clearbill/mgr/server/internal/app/bll"
	"clearbill/mgr/server/internal/app/config"
	"clearbill/mgr/server/internal/app/dal"
	"clearbill/mgr/server/internal/app/db"
)

// Injectors from wire.go:

func BuildInjector(cfg config.Config) (*Injector, error) {
	gormDB, err := db.InitDBClient(cfg)
	if err != nil {
		return nil, err
	}
	engine := InitGinEngine(cfg)
	userDAL := dal.NewUserDAL(gormDB)
	sessionDAL := dal.NewSessionDAL(gormDB)
	apiTokenDAL := dal.NewAPITokenDAL(gormDB)
	authService := bll.NewAuthService(userDAL, sessionDAL, apiTokenDAL)
	roleDAL := dal.NewRoleDAL(gormDB)
	rolePermissionDAL := dal.NewRolePermissionDAL(gormDB)
	tenantDAL := dal.NewTenantDAL(gormDB)
	permissionCatalog := bll.NewPermissionCatalog()
	roleService := bll.NewRoleService(roleDAL, rolePermissionDAL, userDAL, tenantDAL, permissionCatalog)
	authAction := action.NewAuthAction(authService)
	systemDAL := dal.NewSystemDAL()
	systemService := bll.NewSystemService(systemDAL)
	systemAction := action.NewSystemAction(systemService)
	billingDAL := dal.NewBillingDAL()
	billingService := bll.NewBillingService(billingDAL)
	billingAction := action.NewBillingAction(billingService)
	tenantService := bll.NewTenantService(tenantDAL, userDAL)
	tenantAction := action.NewTenantAction(tenantService, roleService)
	roleAction := action.NewRoleAction(roleService)
	userService := bll.NewUserService(userDAL, tenantDAL, roleService)
	userAction := action.NewUserAction(userService)
	router := InitRouter(cfg, authService, roleService, authAction, systemAction, billingAction, tenantAction, roleAction, userAction, engine)
	injector := &Injector{
		Config:            cfg,
		DBClient:          gormDB,
		Engine:            engine,
		Router:            router,
		APITokenDAL:       apiTokenDAL,
		AuthAction:        authAction,
		SystemAction:      systemAction,
		BillingAction:     billingAction,
		TenantAction:      tenantAction,
		RoleAction:        roleAction,
		UserAction:        userAction,
		AuthService:       authService,
		RoleService:       roleService,
		SystemService:     systemService,
		BillingService:    billingService,
		TenantService:     tenantService,
		UserService:       userService,
		SystemDAL:         systemDAL,
		BillingDAL:        billingDAL,
		TenantDAL:         tenantDAL,
		RoleDAL:           roleDAL,
		RolePermissionDAL: rolePermissionDAL,
		UserDAL:           userDAL,
		SessionDAL:        sessionDAL,
	}
	return injector, nil
}
