.PHONY: all clean dist mod lint wire swagger test

all: dist

mod:

lint:

wire:

swagger:

test:

dist:
	mkdir -p dist
	cp -f *.sh dist/ 2>/dev/null || true
	cp -f README.md dist/README.md

clean:
	rm -rf dist
	mkdir -p dist
